name: Hello world

on:
    workflow_dispatch:
jobs:
    say-hello-world:
        name: say hello world
        runs-on: ubuntu-latest

        steps:

            - name: echo hello world
              run: echo "hello world"
    
    say-name-world:
        name: say hello world with name
        runs-on: ubuntu-latest
        steps:
            - name: echo name
              run: echo "satish"
    
    greet-everyone:
        name: greet everyone
        runs-on: ubuntu-latest
        needs: 
            - say-hello-world
           
        steps:
            - name: greet everyone
              run: echo "hello to world from satish"
    greet-satish:
        name: greet satish
        runs-on: ubuntu-latest
        needs:
           
            - say-name-world
        steps:
            - name: greet satish
              run: echo "hello satish"
    do-calculation:
        name: do addition
        runs-on: ubuntu-latest
        needs:
            - greet-everyone
            - greet-satish
        steps:
            - name: run 2+2
              run: 4+4
              shell: python
